Arewa Data Science Academy

Deep Learning Cohort2.0

Name: Zaharaddeen Nura Ibrahim

Email: zaharaddeennura@gmail.com

Title: Week 1 Solution

Exercises Solution

2. Create a random tensor with shape (7, 7).

In [2]:
# Import torch
import torch

# Create random tensor
tensor2 = torch.rand(7, 7)
tensor2.ndim, tensor2.shape

(2, torch.Size([7, 7]))

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [30]:
# Create another random tensor
tensor3 = torch.rand(1, 7)
tensor3.ndim, tensor3.shape



(2, torch.Size([1, 7]))

In [31]:
transpose = tensor3.T
transpose.ndim, transpose.shape

(2, torch.Size([7, 1]))

In [34]:
# Perform matrix multiplication
result = torch.matmul(tensor2, tensor3.T)
result

tensor([[1.5688],
        [0.9070],
        [1.0978],
        [1.5727],
        [1.5372],
        [1.3775],
        [2.1036]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [50]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7,  7)
tensor2 = torch.rand(1, 7)

# Perform matrix multiplication
tenmul = torch.matmul(tensor1, tensor2.T)
tenmul,tenmul.shape



(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to gpu
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [8]:
# Perform matmul on tensor_A and tensor_B
tensor7 = torch.mm(tensor_A, tensor_B.T)
tensor7, tensor7.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
torch.max(tensor7)

tensor(0.5617, device='cuda:0')

In [14]:
# Find min
torch.min(tensor7)

tensor(0.3647, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
torch.argmax(tensor7)

tensor(3, device='cuda:0')

In [17]:
# Find arg min
torch.argmin(tensor7)

tensor(0, device='cuda:0')

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [18]:
# Set Seed
torch.manual_seed(7)

# Create a random tensor
tensor10a = torch.rand(1, 1, 1, 10)

# Remove single dimension
tensor10b = tensor10a.squeeze()

# Print out tensors and their shapes
tensor10a, tensor10a.shape, tensor10b, tensor10b.shape





(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))